config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  get 'auth/logout' => 'auth#logout'
  get 'auth/failure' => 'auth#failure'
  get 'auth/:provider/callback' => 'auth#callback'

  get "login" => "sessions#new", as: :login
  post "login" => "sessions#create"

  get "logout" => "sessions#destroy"
  post "logout" => "sessions#destroy"

  get "about" => "site#about"

  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'

  resources :users

  get "users/:id/goals" => "users#goals", as: :goals
  post "users/:id/goals" => "users#goals_add", as: :addgoal
  post "users/:id" => "users#goals"

  get "users/:id/goals/:goal_id" => "users#goalshow", as: :eachgoal

  get "users/:id/awards" => "users#awards"

  put "users/:id/goals/update" => "users#goals_update", as: "goal_update"
  put "users/update" => "users#goals_update"
  put "users/:id/goalscomplete" => "users#goals_complete", as: :goal_complete
  put "users/:id/goals/remove" => "users#goals_inactive", as: "goal_inactive"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :goals_users
  has_many :goals, through: :goals_users
  has_and_belongs_to_many :awards

  before_validation do
    self.phone = phone.gsub(/[^0-9]/, "") if attribute_present?("phone")
  end

  validates :name, presence: true

  validates :email, presence: true, uniqueness: {case_sensitive: false}

  validates_confirmation_of :password, on: :create
  validates_presence_of :password_confirmation, on: :create

  validates :password, presence: true, length: { minimum: 6 }, on: :create

  validates :phone, numericality: true, length: { is: 10 || 0},  allow_blank: true, allow_nil: true

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

  private

  def initialize_user
    self.text_alert = false
    self.email_alert = false
    self.negative = false
    self.positive = false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_authenticated?, :except => [:new, :create]
  before_action do
    @user = current_user
  end


  def index
    redirect_to show
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @goal = Goal.find_by_id(params[:goal_id])
    @goals_users = @user.goals_users.where({active:true})
    @avg_streak, @avg_maxstreak = 0, 0
    @user.goals_users.each do |goal|
      @avg_streak = (@goals_users.average(:streak_completed).to_f.round(2))/2
      @avg_maxstreak = (@goals_users.average(:max_streak).to_f.round(2))/2
    end

  end

  def create
    @user = User.create(user_params)

    if @user.errors.any?
      flash[:danger] = 'Invalid Entry'
      render :new
    else
      session[:user_id] = @user.id
      flash[:success] = "Sign Up Successful!"
      UserMailer.registration_confirmation(@user).deliver_now
      redirect_to login_path
    end
  end

# USER SETTINGS EDIT VIEW
  def edit
    @user = User.find_by_id(params[:id])
    @goal = Goal.find_by_id(params[:goal_id])
  end

# USER SETTINGS UPDATE METHOD
  def update
    if @user.phone != params[:user][:phone]
      @user.phone = params[:user][:phone]
      @user.po_email = params[:user][:po_email]
      @user.save
      flash[:success] = "Info changed successfully!"
      send_text_greeting
    end
    if @user.po_email != params[:user][:po_email]
      @user.phone = params[:user][:phone]
      @user.po_email = params[:user][:po_email]
      @user.save
      flash[:success] = "Info changed successfully!"
      UserMailer.email_notify_po(@user).deliver_now
    end

    redirect_to edit_user_path(@user)
  end

  def goals
    @goal = Goal.new
    # active_goal = @user.goals.where.not(goal_type: 'user')

    @goals_user = @user.goals.where.not(goal_type: 'user');

    @users_custom_goals = @user.goals.where(goal_type: 'user');
    @goals = Goal.all.where.not(goal_type: 'user');
  end

# INDIVIDUAL GOAL PAGE
  def goalshow
    @user = current_user
    @goal = Goal.find_by_id(params[:goal_id])
    # @goal = GoalsUser

    #For user currently
    @goals_users = @user.goals_users.where({active:true})
    @streak_completed = 0
    @user.goals_users.each do |goal|
      @streak_completed = (@streak_completed + goal.streak_completed)/2
    end

    #For all community
    @users_ever = @goal.users_ever
    @users_currently = @goal.users_currently
    @total_completions = @goal.total_completions

    #For user to compare with
    @average_streak_currently = (@goal.average_streak_currently.to_i)/2

  end

# CUSTOM GOAL ADD on GOALS UPDATE PAGE
  def goals_add
    @goal = Goal.create(goal_params)
    goal = GoalsUser.create({user_id:@user.id,goal_id:@goal.id})
    respond_to do |f|
      f.html {redirect_to goals_path(@user)}
      f.json {render json: {new_goal:goal,success: true}}
    end
  end

# HARDCODE GOAL ADD on USR PROFILE PAGE
  def goals_complete
    # goal = Goal.find(params[:id])
    @goals_user = GoalsUser.where(user_id:@user.id).where(goal_id: params[:id])
    @goals_user.map do |goal, index|
      goal.update_attributes(completed_today: true)
      goal.gu_update
      goal.save
    end
    # goals_user.save_all
    update_awards
    respond_to do |f|
      f.html {redirect_to goals_path(@user)}
      f.json {render json: {success: true}}
    end

  end

  # HARDCODE GOAL ADD on GOAL UPDATE PAGE
  def goals_update
    @goal = Goal.find(params[:id])
    goal = GoalsUser.find_or_create_by({user_id:@user.id,goal_id:@goal.id})
    if !goal.active
      goal.update_attribute("active", true)
    end
    update_awards
    respond_to do |f|
      f.html {redirect_to goals_path(@user)}
      f.json {render json: {success: true}}
    end
  end

# CUSTOM AND HARDCODE GOAL INACTIVE on GOALS UPDATE PAGE
  def goals_inactive
    @goal = Goal.find(params[:id])
    @temp = GoalsUser.where({user_id:@user.id,goal_id:@goal.id})
    @temp.update_all(active: "false")
    respond_to do |f|
      f.html {redirect_to goals_path(@user)}
      f.json {render json: {success: true}}
    end
  end

  def awards
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end

  def goal_params
    params.require(:addgoal).permit(:name)
  end

end

app/views/users/awards.html.erb
<!-- shows users awards from DB awardsusers -->

app/views/users/edit.html.erb
<!-- edits user info posts to user DB -->


<h1 class="text-center">Edit Your Settings</h1>


<!-- User should be able to input/change -->
<!-- 1) notification setttings
add phone, add email, neg/pos reinforcement
location (stretch, sunrise, sunset)-->

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h3 class="text-center">Enter your 10-digit phone number and opt in to text messages</h3>
    <%= bootstrap_form_for @user do |f| %>
    <div class="row">
      <%= f.text_field :phone,hide_label: "Enter a phone number and opt in to text messages",placeholder: @user.phone ? @user.phone : "Enter your phone number" %>
      <h3 class="text-center">&nbsp&nbsp&nbspAdd an email of someone you want to receive an email if you don't complete your goals</h3>
      <%= f.text_field :po_email, hide_label: "Add an email of someone you want to receive an email if you don't complete your goals",  placeholder: "Add an email" %>
    </div>
    <div class="text-center">
      <%= f.submit "Submit", :class=> "btn btn-primary" %>
    </div>
    <br><br>
    <% end %>
  </div>
</div>

app/views/users/goals.html.erb
<!-- users goals update / create page also posts to goals DB in event of new user inputted goal ; notifications opt in, posts to user DB ; notifications opt in goes to User DB, new goals go to goals DB & goalsusers DB, add new goal that already exists goes to goalsusers db -->
<div class="container">
  <div class="row text-center">
    <div class="col-xs-5 col-md-5">
      <h2>Custom Active Goals</h2>
      <div class="row text-center">
        <h3><table class="table table-striped">
          <thead>

          </thead>
          <tbody>
            <% @users_custom_goals.each do |goal| %>
            <tr>
             <% if goal.goals_users.where({user_id:@user.id,active:true}).any? %>
             <td><%= goal.name %></td>
             <td>
              <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, goal_inactive_path(:id => goal.id), :method => :put, :class => "btn btn-danger ajax-goal-custom-remove" %>

            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table></h3>
    </div>
    <div class="row text-center">
      <h2>More Active Goals</h2>


      <h3><table class="table table-striped">
        <caption class="text-center"></caption>

        <tbody>
          <% @goals_user.each do |goal| %>
          <% if goal.goals_users.where({user_id:@user.id,active:true}).any? %>
          <tr>

            <td><%= goal.name.capitalize %></td>
            <td>
              <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, goal_inactive_path(:id => goal.id), :method => :put, :class => "btn btn-danger ajax-goal-add-remove" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table></h3>
    </div>
  </div>

  <div class="col-xs-2 col-md-2">
    <div class="row text-center">

    </div>
  </div>

  <div class="col-xs-5 col-md-5">
    <h2>Add a custom goal</h2>

    <div class="row text-center">
      <h3><table class="table text-center">
        <tbody>
          <tr>
            <td>
              <%= bootstrap_form_for :addgoal, html:{class: 'ajax-goal-form'} do |f| %>
              <%= f.text_field :name, hide_label: true, placeholder: "Add a new custom goal" %>
            </td>

            <td>
              <%= button_tag(type: 'submit', class: "btn btn-success") do %>
              <i class="glyphicon glyphicon-ok"></i>
              <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table></h3>
    </div>
    <h2>Add other goals</h2>

    <div class="row text-center">
      <h3><button type="button" id="goal-mind" class="btn btn-md btn-primary">Mind</button>
        <button type="button" id="goal-body" class="btn btn-md btn-primary">Body</button>
        <button type="button" id="goal-social" class="btn btn-md btn-primary">Social</button><br><br>
        <button type="button" id="goal-personal-growth" class="btn btn-md btn-primary">Personal Growth</button>
        <button type="button" id="goal-world-takeover" class="btn btn-md btn-primary">World Takeover</button></h3>
        <h3><table class="table table2">
          <caption class="text-center"></caption>
          <tbody>
            <% @goals.each do |goal| %>
            <% is_inactive = goal.goals_users.where({user_id:@user.id,active:false}).any? %>
            <tr class="goal-type-<%= goal.goal_type.gsub(/\s+/, '-') %>" >
              <td><%= goal.name.capitalize %></td>
              <td>
                <%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe, goal_update_path(:id => goal.id), :method => :put, :class => "btn btn-success ajax-goal-add-remove"  %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table></h3>

      </div>
    </div>
  </div>
</div>

app/views/users/goalshow.html.erb
<!-- shows users stats on goal from goalsusers db and global stats on the goal from goals db, to add: social sharing button -->


<div class="container text-center">
  <div class="row">
    <div class="col-md-12">
      <h1>Goal: <%= @goal.name %></h1>
        <div class="row">
        <div class="col-xs-6 col-md-6">
            <h2>Streak Statistics</h2>
            <div id="userStreakChart" style="height: 250px, width:400px;"></div>
            </div>
              <div class="col-xs-6 col-md-6">
            <h2>Community Goal Use</h2>
            <div id="communityChart" style="height: 250px, width:400px;"></div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>



<script>
  new Morris.Donut({
  // ID of the element in which to draw the chart.
  element: 'userStreakChart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
    { label: '<%=@user.name%>', value: <%=@streak_completed%> },
    { label: 'All Users', value: <%=@average_streak_currently%> },
    ],
  });

</script>


<script>
  new Morris.Donut({
  // ID of the element in which to draw the chart.
  element: 'communityChart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
    { label: 'Total Users Ever', value: <%=@users_ever%> },
    { label: 'Current Users', value: <%=@users_currently%> },
    { label: 'Total Completions', value: <%=@total_completions%> },
    ],
  });

</script>

app/views/users/new.html.erb
<!-- sign up includes facebook, bootstrap form, redirects user profile -->
<div class="container text-center">
  <div class="row">
    <% if @current_user %>
    Hello again, <%= @current_user.name %>
    <br><br>
    <% else %>
    <h2>Sign up and log in with <a href="/auth/facebook">Facebook</a></h2>
    <br><br>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= bootstrap_form_for @user do |f| %>
      <%= f.text_field :name, placeholder: "Enter your name", icon: "user" %>
      <%= f.text_field :email, placeholder: "Enter your email", icon: "envelope" %>
      <%= f.password_field :password, placeholder: "Enter your password", icon: "lock" %>
      <%= f.password_field :password_confirmation, label: "Confirm Password", icon: "lock" %>
      <%= f.submit "Sign Up!", :class=> "btn btn-primary" %>
      <br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- users profile page links to everything, importantly edit user and edit goals, button to update usersgoals lists usersgoals some sort of chart ; posts to usersgoals -->

<div class="container">
  <div class="row text-center">
    <!-- <div class="col-md-3">
      <img src="http://i.imgur.com/aYEXWnA.png">
    </div> -->
    <div class="col-xs-8 col-xs-offset-2">
      <h1><%= @user.name %></h1>

      <h2><%= link_to "Edit Your Contact Settings", edit_user_path(@user) %></h2>

      <h2>You have <%=@user.goals_users.where({completed_today:true}).where({active:true}).length%> out of <%=@user.goals_users.where(active:true).length%> goals completed today!</h2>

      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 col-md-2 opacity text-center">
      <h2>Badges</h2>
      <% if @user.awards.any? %>
      <% @user.awards.each do |award|%>
      <h3 class="badge-name"><%= award.name %></h3>
      <%= image_tag 'badges/'+award.image_url, title: award.desc, size: "75" %>
      <% end %>
      <% end %>
    </div>
    <% if @goals_users.any? %>
    <div class="col-xs-10 col-md-10">
      <table class="table table-striped">
        <h2 class="text-center">Your Daily Goals</h2>
        <thead>
          <tr>
            <th>Goal</th>
            <th>Done Today?</th>
          </tr>
        </thead>
        <tbody>
          <% @goals_users.sort.each do |goal_user| %>
          <% goal = goal_user.goal %>
          <tr>
            <td><%= link_to goal.name.capitalize, eachgoal_path(@user, goal) %></td>
            <td>
              <% if goal_user.completed_today %>
              DONE!
              <% else %>
              <%= link_to '<button class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>'.html_safe, goal_complete_path(:id => goal.id), class: "ajax-done-btn" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <h2><%= link_to "Add goals now!", goals_path(@user) %></h2>
      <!-- <h2><a href="/users/<%=@user.id%>/goals">Add goals!</a></h2> -->
      <% end %>
    </div>

    <br>

  </div>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h2> Days Completed Streak </h2>
      <div id="streakChart" style="height: 250px;"></div>

    </div>
    <br><br>
  </div>
</div>

  <script>
    new Morris.Bar({
    // ID of the element in which to draw the chart.
    element: 'streakChart',
      // Chart data records -- each entry in this array corresponds to a point on
      // the chart.
      data: [
      { streak: 'Average Streak', value: <%=@avg_streak%> },
      { streak: 'Longest Streak', value: <%=@avg_maxstreak%> },
      ],
      // The name of the data record attribute that contains x-values.
      xkey: 'streak',
      // A list of names of data record attributes that contain y-values.
      ykeys: ['value'],
      // Labels for the ykeys -- will be displayed when you hover over the
      // chart.
      labels: ['Days']
    });

  </script>